version: '3.1'
 
services:
  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - db
      - redis
    command: redis:6379 db:1433 rabbit1:15672
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Pass@word"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
  rabbit1:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"